### ISSUE TITLE
setup.vala:243: can't parse plist

### ISSUE THREAD

**Issue by Dubhead** [ueno/ibus-skk#55]
Fedora 21 x86_64 で、ある時から急に仮名漢字変換ができなくなりました。
たとえば「▽にほんご」の状態で space を打つと「▼にほんご 【】」になります。
ibus-skk は 1.4.1 です (yum update したばかり)。

ここで端末から ibus-setup を起動し、
Input Method タブの Japanese - SKK を選んで Preferences をクリックすると、
Dictionaries タブが空であり、端末には以下のメッセージが出ます:

> ** (ibus-setup-skk:23864): WARNING **: setup.vala:243: can't parse plist file=/usr/share/skk/SKK-JISYO.L,mode=readonly,type=file,: 

Add.. ボタンから System の SKK-JISYO.L を追加し、OK、Close とした後、
再び ibus-setup を起動して Japanese - SKK の Preferences を選ぶと、
同じ WARNING が出て (プロセス番号のみ違います)、
Dictionaries タブがやはり空です。

**Comment by Dubhead** [comment]
dconf-editor で、desktop / ibus / engine / skk を開き、dictionaries を

> ['file=/home/ユーザ名/.config/ibus-skk/user.dict,mode=readwrite,type=file', 'file=/usr/share/skk/SKK-JISYO.L,mode=readonly,type=file']

に設定すると、仮名漢字変換はできるようになりました。
設定ツールの問題かと思われます。

**Comment by ueno** [comment]
たぶん 1.4.2 で直っていると思います：
https://github.com/ueno/ibus-skk/commit/f88d72bbc1a45747e10086983204120dc08fecbf#diff-e7e89995b9301d5bab2a97020bfd7274L97

**Comment by Dubhead** [comment]
@ueno ありがとうございます。1.4.2 は昨年9月リリースか…

**Comment by ueno** [comment]
https://admin.fedoraproject.org/updates/ibus-skk-1.4.2-1.fc21,libskk-1.0.2-1.fc21
