### ISSUE TITLE
[ibus-skk] ナ行変格活用の動詞の誤変換

### ISSUE THREAD

**Issue by zoome0215** [ueno/ibus-skk#63]
ナ行変格活用の動詞を変換しようとすると、例えば  

`失敗した、死にたい 
 を 
`SippaiSita,SiNitai``

 と変換したさい
「失敗した死んいたい」と、1つの`ni`が`に`ではなく`んい`と変換されます。

**Comment by ueno** [comment]
再現できません。入力例も間違っていると思います。
```
$ echo 'S i p p a i SPC RET s i t a , S i N i t a i' | skk -f /usr/share/skk/SKK-JISYO.L
{ "input": "S i p p a i SPC RET s i t a , S i N i t a i", "output": "失敗した、死にたい", "preedit": "" }
```

**Comment by zoome0215** [comment]
ごめんなさい。解決いたしました。
何度も試してみたのですが、結局はスペースキーを長く押しすぎた時にNの後のI被って誤変換がおきていたようでした。
お時間を取らせて申し訳ありませんでした。ありがとうございました。

**Comment by dai-vdr** [comment]
こんにちは。こちら既にクローズされておりますが、コメントを追加させてください。
こちらの件は、ibus-skkとuim-skkで変換動作に違いがあるためでもあると考えています。例えば「気になる」「出ない」と変換する際、本来であれば「K i N i n a r u」「D e N a i」と入力し、ibus-skkでもそのように入力されることを期待しています。

```json
$ echo 'K i N i n a r u' | skk
{ "input": "K i N i n a r u", "output": "気になる", "preedit": "" }
$ echo 'D e N a i' | skk
{ "input": "D e N a i", "output": "出ない", "preedit": "" }
```

uim-skkの場合「K **I** N **I** n a r u」「D **E** N **A** i」のようにある程度シフトキーを押したまま入力しても「気になる」「出ない」と変換されます。この寛容な形式に慣れていると、ibus-skkの場合「気んいなる」「出んあい」のように変換ミスが起きてしまいます。

```json
$ echo 'K I N I n a r u' | skk
{ "input": "K I N I n a r u", "output": "気んいなる", "preedit": "" }
$ echo 'D E N A i' | skk
{ "input": "D E N A i", "output": "出んあい", "preedit": "" }
```

この動作は仕様に従ったもので、厳密な意味での誤変換ではないと思います。このような入力でも意図通りに変換できるようにすることは可能でしょうか？ 再オープンとご検討いただければ幸いです。よろしくお願いいたします。

**Comment by ueno** [comment]
この挙動はあえて ddskk に寄せたものなので、可能ではあると思います（参考[1](https://github.com/ueno/libskk/blob/5f5e5c2d3facfec9f577fb66032e6f1994ed5d44/libskk/state.vala#L954), [2](https://github.com/ueno/libskk/blob/5f5e5c2d3facfec9f577fb66032e6f1994ed5d44/tests/basic.c#L80))。

**Comment by dai-vdr** [comment]
ご確認ありがとうございます。
こちらそのもののテストケースもある、仕様通りの動作だったのですね。
こちら改めて https://github.com/ueno/libskk 側にレポートさせていただきます。
