### ISSUE TITLE
Does almost nothing/Document setup

### ISSUE THREAD

**Issue by Fabian42** [ueno/ibus-skk#67]
I am using Manjaro, X and KDE. I installed the "`community/ibus-anthy`" package, ran "`ibus-setup`", there I already saw the layouts "German (no dead keys)", "German" and "Japanese – SKK". I changed nothing of relevance, then ran "`ibus-daemon`" and thought I could somehow type Japanese.  
But what actually happened was only that I got a US keyboard layout (Z and Y switched compared to how they are on my keyboard, most special characters different, etc.), that a tray icon of Ibus appeared and that I had a little hovering window in the bottom right. I tried some other options, like setting "initial input method" to "Latin", I pressed key combos like Win+space (which at least does something, it opens a menu that lets me select "Japanese – SKK" there as well, but nothing changes from that), Ctrl+G (seen mentioned in some issue reports here) or Ctrl+Shift+E (for emoji), each before typing, after typing, after a period, etc., I tried it in different programs, but none of that allowed me to input any Japanese characters at all, especially not Kanji.  
I saw videos where there were selection popups and the option "Candidates orientation: vertical/horizontal" seemed like this is actually a program that SHOULD add those to my system, but I can still only type Latin characters.

The documentation here on Github is also not great for setup. It tells me the three commands for installation (which I didn't need, because I used the package manager) and then nothing further. So how do I actually make this work correctly?  
None of the other Github issue reporters seemed to have this problem, so could it maybe be something specific to my system? But I wouldn't know what, since Ibus does apparently run correctly (and disables my usual input method) and SKK is actually in the list, it just doesn't do anything. Should I press some other key combination? Ctrl+G appeared nowhere in the Readme, the settings or elsewhere, so maybe there's something else that I don't know about?

**Comment by ueno** [comment]
As mentioned in the [Wikipedia page](https://ja.wikipedia.org/wiki/SKK) linked from README, SKK is somewhat different style of input method: to input "彼は足が速い", you need to type "Kare␣haAsi␣gaHayaI" (notice the capital letters which trigger Kana -> Kanji conversion). While this might look strange for those familiar with input methods based on sentence based conversion, some people find it more convenient because of less ambiguity in Kana -> Kanji conversion.

**Comment by Fabian42** [comment]
That still does nothing.
![image](https://user-images.githubusercontent.com/10481506/126066483-883f6ceb-1178-4ca4-9028-11150def25ad.png)
And still, I think the usage should be documented in the Readme, in the same language as the rest of the Readme.
