### ISSUE TITLE
ibus-skk候補ウィンドウの表示が縦にならない

### ISSUE THREAD

**Issue by rkarsnk** [ueno/ibus-skk#68]
Debian 11でibus 1.5.23-2/ibus-skk 1.4.3-1をi3wmで利用しています。

iBusの設定で候補ウィンドウを「縦」に設定しても、ibus-skkでは、候補ウィンドウは「横」に標示されます。

ibus-skkは「横」固定なのでしょうか？

**Comment by ueno** [comment]
そうだったと思います。候補のショートカットが qwerty 配列に合わせてあるため（オリジナルのSKK同様）、縦にすると使いにくいというのが理由です。

**Comment by rkarsnk** [comment]
なるほど、オリジナルのSKKに合わせているのですね。

ibus-kkcのソースコードを眺めた上での質問ですが、

https://github.com/ueno/ibus-skk/blob/740556ef1e254f34fe75d6099fb6728bb058d95a/src/engine.vala#L56

(使い勝手は別として)上記のコードをコメントアウトした場合、
IBusの設定で候補ウィンドウの方向を「縦」に設定することで、
候補ウィンドウは縦向きになりますか？
